### ISSUE TITLE
Functions

### ISSUE THREAD

**Issue by dungdl28d11** [dungdl28d11/expresswaiter#11]
- Demo app with basic functions:
 + UI
 + Button Click Events Handler
 + Fixed Data

**Comment by lukinoteam** [comment]
Cái này chắc cần ít nhất 2 ngày

**Comment by dungdl28d11** [comment]
@lukinoteam m chỉ code phần business thôi nhé

**Comment by lukinoteam** [comment]
- Optimized performance.
- Edit some component for better look (button, label,...).
- Remove food pictures list (this list is not needed).
- Remove "Guest Manager" and "Time Manager" (can't manage guest and time)
- Change status from "Eat" and "Wait" to "Paid" and "Unpaid"
- Add "Bill printing" feature (when click "Thanh toán" button)

[v11.zip](https://github.com/dungdl28d11/expresswaiter/files/2691068/v11.zip)

**Comment by xwind1999** [comment]
không có import được nha

**Comment by xwind1999** [comment]
Code có đụng chạm gì đến View không để sửa lại

**Comment by lukinoteam** [comment]
có view mới rồi, vào check đi xem chưa hiểu chỗ nào thì bảo.

**Comment by lukinoteam** [comment]
nâng cấp một số thành phần trong giao diện:
- Button
- Label
- Panel

**Comment by dungdl28d11** [comment]
@xwind1999 tách hết tất cả các text ra thành static variables của 1 class cho dễ quản lý

**Comment by dungdl28d11** [comment]
phần in hóa đơn thanh toán thì đồng thời gọi database để update trạng thái bàn đã hoàn thành.
