### ISSUE TITLE
Restructure project to MVC

### ISSUE THREAD

**Issue by dungdl28d11** [dungdl28d11/expresswaiter#12]
Using MVC to arrange this project.
Package Model is divided into TWO parts: _com.model.data_access_ and _com.model.business_
Inside BUSSINESS pack has to be two packs: _com.model.business.models_ and _com.model.business.handler_

**Comment by dungdl28d11** [comment]
commit code đi cu.

**Comment by xwind1999** [comment]
commit what ??
