### ISSUE TITLE
UI Frame

### ISSUE THREAD

**Issue by dungdl28d11** [dungdl28d11/expresswaiter#19]

**Comment by dungdl28d11** [comment]
background của màn hóa đơn bị thành màu đen.
lúc hủy đơn xong phải mở lại màn home.
tất cả mọi thao tác hủy đều mở dialog để hỏi xác nhận hủy.

**Comment by lukinoteam** [comment]
hủy đơn mở lại home => đã xong.

background màn hóa đơn vẫn bình thường mà.
chỉ có mỗi 1 thao tác hủy đơn thôi, còn thao tác hủy nào nữa đâu

**Comment by dungdl28d11** [comment]
vẽ lại UIHome thành 3 tầng theo 3 tab nhé

**Comment by dungdl28d11** [comment]
đổi màu bàn theo trạng thái

**Comment by dungdl28d11** [comment]
@lukinoteam hiển thị danh sách món ăn của từng bàn đã order. chuyển từ 2-dimension array sang arraylist. trong object bill có thuộc tính arraylist là listOrder rồi. lấy list đấy ra hiển thị

**Comment by dungdl28d11** [comment]
> đổi màu bàn theo trạng thái

@xwind1999 lấy màu bàn theo màu của 3 thanh trạng thái bên dưới (đỏ, xanh, vàng)

**Comment by xwind1999** [comment]
@dungdl28d11 Có mỗi hai trạng thái là BUSY với free thôi nhé bởi status là biến boolean

**Comment by dungdl28d11** [comment]
ok xong nhé. chốt hết UI ở đây
