### ISSUE TITLE
RestAPI Firebase to Java

### ISSUE THREAD

**Issue by lukinoteam** [dungdl28d11/expresswaiter#4]
INSTALLING & SETUP
https://firebase.google.com/docs/database/rest/start?hl=vi

REFERENCE
https://firebase.google.com/docs/reference/rest/database/

**Comment by dungdl28d11** [comment]
Cái này build demo tính năng xong rồi ghép vào app sau

**Comment by dungdl28d11** [comment]
xem demo bên "demonstration" branch

**Comment by dungdl28d11** [comment]
demo có trong "demonstration" brach rồi nhé. lấy code bên đấy ghép vào app chạy lấy data đi @lukinoteam
