### ISSUE TITLE
Build skeleton with Java Swing

### ISSUE THREAD

**Issue by dungdl28d11** [dungdl28d11/expresswaiter#5]
Làm UI theo bản phác của Hùng.

**Comment by lukinoteam** [comment]
Home
![home](https://user-images.githubusercontent.com/23174034/48297346-3949b200-e4d8-11e8-8bdf-71cb018223dc.png)

Chi tiết mỗi bàn khi click vào bàn cụ thể
![table_detail](https://user-images.githubusercontent.com/23174034/48297347-3949b200-e4d8-11e8-8ed2-c0fe9b61a279.png)

![prototype](https://user-images.githubusercontent.com/23174034/48297388-559a1e80-e4d9-11e8-9965-cb842185af76.png)

Note:
- Nút làm tươi là nút refresh
- Khi ấn nút "Thanh toán" hoặc "Hủy đơn", sẽ show ra 1 bảng confirm Yes/No

**Comment by lukinoteam** [comment]
File XD: 

[demo.zip](https://github.com/dungdl28d11/expresswaiter/files/2568106/demo.zip)

**Comment by dungdl28d11** [comment]
tạo folder UI xong up file xd vào đấy đi hùng

**Comment by dungdl28d11** [comment]
sửa phần fill data sang sử dụng Collection nhé. tạo phương thức cho từng phần

**Comment by dungdl28d11** [comment]
biến cho lên đầu. comment từng vùng biến

**Comment by dungdl28d11** [comment]
đổi cửa sổ không mở cửa sổ khác.

**Comment by dungdl28d11** [comment]
đổi tên các class trong UI thành tên màn hình. ví dụ Food.java => UIListFood.java

**Comment by xwind1999** [comment]
ê cũng phải biết là tối đa bao nhiêu bàn 1 tầng bởi cái thanh kéo cũng chỉ có giới hạn thôi

**Comment by xwind1999** [comment]
Không căn cẩn thận một tầng nhiều bàn quá thì không gian mỗi cái nó cứ chi chít lại khó nhìn lắm

**Comment by dungdl28d11** [comment]
thế mới cần phải m phải nghĩ. số lượng bàn là tùy thuộc vào chủ nhà hàng quy định. m cứ để nó là một cái Collection, danh sách động thì muốn thêm bớt bao nhiêu chả được. cứ mặc định chiều ngang là 4 bàn chẳng hạn, thì chiều dọc muốn bao nhiêu hàng cũng được. sinh ra thanh scrollbar để làm gì
